# Generated by Django 2.2 on 2020-07-25 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idpl', models.AutoField(db_column='idPl', primary_key=True, serialize=False)),
                ('nombrepl', models.CharField(db_column='nombrePl', max_length=60)),
                ('productorespl', models.CharField(db_column='productoresPl', max_length=500)),
                ('detallePl', models.CharField(db_column='detallePl', max_length=500)),
                ('directorpl', models.CharField(db_column='directorPl', max_length=45)),
                ('planetaspl', models.CharField(db_column='planetasPl', max_length=60)),
            ],
            options={
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('idpj', models.AutoField(db_column='idPj', primary_key=True, serialize=False)),
                ('nombrepj', models.CharField(db_column='nombrePj', max_length=45)),
            ],
            options={
                'db_table': 'personajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetas',
            fields=[
                ('idPla', models.AutoField(db_column='idPla', primary_key=True, serialize=False)),
                ('nombrePla', models.CharField(db_column='nombrePla', max_length=45)),
            ],
            options={
                'db_table': 'planetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persopelis',
            fields=[
                ('idpeli', models.OneToOneField(db_column='idpeli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='startwars.Peliculas')),
            ],
            options={
                'db_table': 'persopelis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planetaspelis',
            fields=[
                ('idpeli', models.OneToOneField(db_column='idpeli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='startwars.Peliculas')),
            ],
            options={
                'db_table': 'planetaspelis',
                'managed': False,
            },
        ),
    ]
